# Generated by Django 6.0.6 on 2026-06-04 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_interno', models.CharField(max_length=100, unique=True)),
                ('tipo_control', models.CharField(choices=[('RETORNABLE', 'Retornable (Se devuelve)'), ('CONSUMIBLE', 'Consumible (No se devuelve)')], default='CONSUMIBLE', max_length=20)),
                ('unidad_medida', models.CharField(default='Unidades', max_length=50)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_critico', models.IntegerField(default=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='inventario.bodega')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='inventario.categoria')),
            ],
        ),
    ]
