# Generated by Django 5.2.6 on 2026-06-06 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('turno_asignado', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_interno', models.CharField(max_length=100, unique=True)),
                ('tipo_control', models.CharField(choices=[('RETORNABLE', 'Retornable (Se devuelve)'), ('CONSUMIBLE', 'Consumible (No se devuelve)')], default='CONSUMIBLE', max_length=20)),
                ('unidad_medida', models.CharField(default='Unidades', max_length=50)),
                ('factor_conversion', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_critico', models.IntegerField(default=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='inventario.bodega')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='inventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada (Ingreso por camión/guía)'), ('SALIDA', 'Salida (Vale de Consumo)'), ('DEVOLUCION', 'Devolución (Retorno a bodega)'), ('BAJA', 'Baja (Producto dañado/merma)')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capataz_autoriza', models.CharField(max_length=100)),
                ('destino_uso', models.CharField(blank=True, max_length=200, null=True)),
                ('turno', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('devuelto', models.BooleanField(default=False)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.articulo')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.trabajador')),
            ],
        ),
    ]
