# Generated by Django 6.0.6 on 2026-06-04 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada (Ingreso por camión/guía)'), ('SALIDA', 'Salida (Vale de Consumo)'), ('DEVOLUCION', 'Devolución (Retorno a bodega)'), ('BAJA', 'Baja (Producto dañado/merma)')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rut_personal', models.CharField(max_length=12)),
                ('nombre_personal', models.CharField(max_length=100)),
                ('capataz_autoriza', models.CharField(max_length=100)),
                ('destino_uso', models.CharField(blank=True, max_length=200, null=True)),
                ('turno', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.articulo')),
            ],
        ),
    ]
