# Generated by Django 5.2.6 on 2026-06-13 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='devuelto',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='estado_prestamo',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Devolución'), ('DEVUELTO', 'Devuelto'), ('N/A', 'No Aplica (Consumible)')], default='N/A', help_text='Controla el estado de las herramientas entregadas en terreno.', max_length=15),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='capataz_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores_capataz', to='inventario.trabajador'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='supervisor_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores_supervisor', to='inventario.trabajador'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='cargo',
            field=models.CharField(blank=True, help_text='Ej. M1 Carpintero, Capataz', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='turno_asignado',
            field=models.CharField(blank=True, help_text='Ej. 14x14 A, Día, Noche', max_length=50, null=True),
        ),
    ]
