# Generated by Django 6.0.6 on 2026-06-16 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_movimiento_devuelto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='cargo',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='rol',
            field=models.CharField(choices=[('OPERARIO', 'Operario / Pañolero'), ('CAPATAZ', 'Capataz'), ('SUPERVISOR', 'Supervisor')], default='OPERARIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='capataz_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'CAPATAZ'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operarios_a_cargo', to='inventario.trabajador'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='supervisor_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capataces_a_cargo', to='inventario.trabajador'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='turno_asignado',
            field=models.CharField(choices=[('A', 'Turno A'), ('B', 'Turno B'), ('E', 'Turno E'), ('DIA', 'Turno Día'), ('NOCHE', 'Turno Noche')], default='DIA', max_length=20),
        ),
    ]
