# Generated by Django 6.0.6 on 2026-06-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_trabajador_cargo_trabajador_especialidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='estado',
            field=models.CharField(default='OPERATIVO', max_length=20),
        ),
    ]
