# Generated by Django 6.0.6 on 2026-08-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_articulo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='estado_asistencia',
            field=models.CharField(blank=True, default='TURNO', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='habitacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='sistema_turno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='test_esfuerzo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
