# Generated by Django 6.0.6 on 2026-09-30 00:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_trabajador_estado_asistencia_trabajador_habitacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='clave_operacion',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='stock_critico',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.articulo'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.trabajador'),
        ),
        migrations.AddConstraint(
            model_name='articulo',
            constraint=models.CheckConstraint(condition=models.Q(('stock_actual__gte', 0)), name='stock_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='articulo',
            constraint=models.CheckConstraint(condition=models.Q(('stock_critico__gte', 0)), name='critico_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='movimiento',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='cantidad_positiva'),
        ),
    ]
