# Generated by Django 6.0.6 on 2026-09-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_movimiento_clave_operacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='turno_asignado',
            field=models.CharField(default='DIA', max_length=20),
        ),
    ]
